export const APP_FOR_GOOD = 'App for good';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SET_DAY_OFF = 'SET_DAY_OFF';
export const SELECT_AREA = 'SELECT_AREA';
export const FETCH_HOTEL = 'FETCH_HOTEL';
export const FETCH_CAR = 'FETCH_CAR';
export const SET_ID_TO_EDIT = 'SET_ID_TO_EDIT';
export const CAN_REFRESH = 'CAN_REFRESH';
export const ID_TO_SHOW = 'ID_TO_SHOW';
