on: 
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install npm module
        run: npm install
      - name: disable CI
        run: export CI=false
      - name: build app
        run: npm run build
      - name: build image
        run: docker build -t ssdp .
      - name: tag image
        run: docker tag ssdp ${{ secrets.registry }}/ssdp
      - name: push image
        run: docker push ${{ secrets.registry }}/ssdp
      - name: clone devops repo
        run: git clone https://github.com/ten4ssdp/devops.git
      - name: create ssh folder
        run: |
          mkdir -p ./keys/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./keys/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./keys/.ssh/id_rsa.pub
          chmod 600 ./keys/.ssh/id_rsa
          chmod 644 ./keys/.ssh/id_rsa.pub
          chmod 700 ./keys/.ssh
      - name: create vault key file
        run: |
          echo "${{ secrets.VAULT_PASS }}" > ./keys/.vault_pass.txt
      - name: run ansible playbook
        uses: saubermacherag/ansible-playbook-docker-action@v1.2
        with:
          playbookName: './devops/ansible/deploy.yml'
          keyFile: "./keys/.ssh/id_rsa"
          inventoryFile: "./devops/ansible/inventory/hosts"
          extraVars: "--vault-password-file ./keys/.vault_pass.txt"
